use_frameworks!

target 'BlueShopping' do
     pod 'BMSPush'
     pod 'Presentr'
	 pod 'BMSAnalytics'
     pod 'BluemixAppID', :git => 'https://github.com/ibm-bluemix-mobile-services/appid-clientsdk-swift.git', :branch => ‘development’
     pod 'OpenWhisk', :git => 'https://github.com/openwhisk/openwhisk-client-swift.git', :tag => '0.2.2'
end